on: 
  push:
    tags:
      - "v*"

jobs:
  export_game:
    permissions: write-all
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game
    steps:
    
    - name: checkout
      uses: actions/checkout@v3.0.2
  
    - name: get tag from version
      id: tag_version
      run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
  
    - name: export game
      id: export
      uses: firebelley/godot-export@v4.6.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
 
    - name: create release
      uses: ncipollo/release-action@v1.11.2
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: v${{ steps.tag_version.outputs.TAG_VERSION }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
